config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

get 'tasks', to: 'tasks#index'
get 'tasks/new', to: 'tasks#new'

get 'tasks/:id', to: 'tasks#show', as: 'task'
post 'tasks', to: 'tasks#create'

get 'tasks/:id/edit', to: 'tasks#edit', as: 'task_edit'
patch 'tasks/:id', to: 'tasks#update'

delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end


  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.input :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit task</h1>

  <%= render "form", task: @task %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My tasks</h1>
  <ul>

    <% @tasks.each do |task| %>
      <li>
        <% if task.completed %>
          <i class="far fa-check-circle"></i>
        <% else %>
          <i class="far fa-circle"></i>
        <% end %>
        <%= link_to task.title, task_path(task) %>
        <%= link_to "Delete", task_path(task), method: :delete, data: {confirm: "Delete #{task.title}?" } %>
      </li>
    <% end %>
  </ul>

  <%= link_to "Add a new task", tasks_new_path %>

</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>New task</h1>

  <%= render "form", task: @task %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h1><%= @task.title %></h1>

  <p><%= @task.details %></p>

  <% if @task.completed %>
    <p>
      <i class="far fa-check-circle"></i>
      This task is completed
    </p>
  <% else %>
    <p>
      <i class="far fa-circle"></i>
      This task is not completed yet
    </p>
  <% end %>

  <%= link_to "Edit this task", task_edit_path %>

  <%= link_to "Back to list", tasks_path %>
</div>